### ISSUE TITLE
ES TOML has invalid formats

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCon/JuliaSurveyForm.jl#10]
I guess we can fix this by just deleting it, but I'm not sure what was the original purpose of TRANSLATE here.

https://github.com/JuliaCon/JuliaSurveyForm.jl/blob/main/surveys/JuliaSurvey.es_ES.toml#L633

cc: @ViralBShah 

perhaps we should add some basic checks of TOML file in the tests

**Comment by ViralBShah** [comment]
Yes, I just merged a PR that fixes it. It was a bit painful to fix it with the fork etc.

The original purpose of TRANSLATE was a hint to the translator that it needed translation. I did it based on google translate for now.

**Comment by ViralBShah** [comment]
I agree that we should check all the TOMLs for being valid readable TOML files.
