### ISSUE TITLE
Transfer to JuliaCon org

### ISSUE THREAD

**Issue by ViralBShah** [JuliaCon/JuliaSurveyForm.jl#2]
Hi @Roger-luo Would you be ok with transferring to the JuliaCon org? I have a fork as well which I am maintaining in my account for now, and would like to also merge it all into this one (either before or after).

**Comment by Roger-luo** [comment]
Sure no problem I can do it tonight

**Comment by Roger-luo** [comment]
@ViralBShah I don't have permission to transfer this repo

**Comment by ViralBShah** [comment]
Invited you.

**Comment by Roger-luo** [comment]
done.
