### ISSUE TITLE
changes to JuliaCon2023

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCon/JuliaSurveyForm.jl#6]
from email

> Roger,
> 
> Thank you so much for this! We have made two last-minute edits to the English survey. Would you be able to make these changes also in the Chinese, Korean, and Japanese versions? Thank you so much for your help!
> 
> 1. Intro - change fourth annual to fifth annual
> 2. Change Other/SPECIFY to just other (no specify) in q 1-33. (Keep Other/SPECIFY as is in q 36-42.)
> 
> Thank you!
> 
> Andrew

I can update the TOML file once @ViralBShah merges your changes if you are modifying the TOML files perhaps make a PR first, so I know what's changed in the Chinese TOML file, to make translation more accurate I have been using a human-verified Chinese TOML to do the Japanese and Korean translate (because CJK is closer semantically to each other than English).

**Comment by ViralBShah** [comment]
I have opened #8 for all the pending commits on spanish. We can move all our workflow to this repo now. cc @ahclaster. I plan to delete my fork.

**Comment by ahclaster** [comment]
Thank you both! @Roger-luo Are you able to make these changes now? 

1. Intro - change fourth annual to fifth annual
2. Change Other/SPECIFY to just other (no specify) in q 1-33. (Keep Other/SPECIFY as is in q 36-42.)
